wandb_version: 1

dataset_name:
  value: Cora
dataset_type:
  value: Planetoid
epochs:
  value: 800
ess:
  value: 0.1
hess_approx:
  value: price
hess_init:
  value: 0.1
hidden_features:
  value: 64
layer_type:
  value: GATConv
lr_model:
  value: 0.1
num_layers:
  value: 4
optimizer_type:
  value: ivon
task:
  value: node_classification
test_samples:
  value: 20
train_samples:
  value: 1
weight_decay:
  value: 0.001
