program: hyperparam_search_wandb.py
method: grid
metric:
  name: max_val_acc
  goal: maximize
parameters:
  epochs:
    value: 800
  task:
    value: node_classification
  optimizer_type:
    value: ivon
  dataset_type:
    value: Planetoid
  dataset_name:
    value: PubMed
  layer_type:
    values: ["TransformerConv", "GATConv", "GCNConv", "SAGEConv"]
  lr_model:
    values: [0.075, 0.1, 0.125, 0.15]
  weight_decay:
    values: [0.0001, 0.001, 0.01] 
  hidden_features:
    values: [64, 128, 256]
  num_layers:
    values: [2, 3, 4]
 