wandb_version: 1

dataset_name:
  value: PubMed
dataset_type:
  value: Planetoid
epochs:
  value: 800
hidden_features:
  value: 64
layer_type:
  value: TransformerConv
lr_model:
  value: 0.125
num_layers:
  value: 6
optimizer_type:
  value: ivon
task:
  value: node_classification
weight_decay:
  value: 0.001
